# Generated by Django 4.2.3 on 2023-08-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTelovendo', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
